### ISSUE TITLE
 Waiting for tf to become available

### ISSUE THREAD

**Issue by mahammadirfan** [Terabee/teraranger_array_converter#10]
I have tried to subscribe to the laserscan topic but that never shows up in rostopic list and the above error continues to show up.

**Comment by pl-kabaradjian** [comment]
Hello @mahammadirfan ,

In order to use the Laserscan or Pointcloud mode, the converter needs to fetch TF information before being able to convert the RangeArray, hence the "Waiting for tf to become available". You can see more info on setting up custom TF : [here](https://github.com/Terabee/teraranger_description)

However, if your goal is only to access the Range messages inside the RangeArray message you can use the "individual_ranges" or "sequential_ranges" mode. Those don't require TF but might require some topic remapping.

Cheers,

**Comment by mahammadirfan** [comment]
Thanks for your reply @pl-kabaradjian .I was able to write the tf and get values using the teraranger array converter package but the values still show infinity despite obstacles being around.
We get an error saying "base_hub" passed to lookupTransform argument does not exist.

**Comment by MrP0w3r** [comment]
> Thanks for your reply @pl-kabaradjian .I was able to write the tf and get values using the teraranger array converter package but the values still show infinity despite obstacles being around.
> We get an error saying "base_hub" passed to lookupTransform argument does not exist.

Getting the same error, did you resolve the issue?

Running the launch file results in the error:
[WARN] [1563778135.773455]: "base_hub" passed to lookupTransform argument target_frame does not exist.
however the topic /ranges is running :
frame_id: "base_hub"


(using Teraranger Tower Evo)

**Comment by pl-kabaradjian** [comment]
Hello @mahammadirfan ,
If "base_hub" does not exists it means that there is an issue with the TF tree. The TF tree needs to be set up as the following (you can visualize it using the TF Tree plugin of rqt)
[Like this](https://i.ibb.co/Lzz9tbn/tf-tree.png)
To achieve this we have ready urdf xacros available for Tower Evo in the teraranger_description package. You can also use them as a starting point for a custom setup.

Cheers,

**Comment by pl-kabaradjian** [comment]
Hello @mahammadirfan and @MrP0w3r ,
Friendly ping to know if this issue can be closed.
Cheers,
